[tools]
elixir = '1.16.3-otp-26'
erlang = '26.2.5.11'
go = '1.23'
node = '22'
python = '3.13'
ruby = '3.2.1'
rust = '1.85'
terraform = '1.13'

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
